#*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

# This workflow will release new versions when required using semantic-release

name: Semantic-Release CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [1.20.x]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@8e58d20d0f6c8773181f43eb74d6a05e3099571d # v3.4.2
      with:
        semantic_version: 19.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}